# Generated by Django 3.1 on 2020-08-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_order_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img_name',
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
