# Generated by Django 3.1 on 2020-08-08 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200808_1224'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PizzaSizes',
            new_name='PizzaSize',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
    ]
